package com.th.thlist;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Exception implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.th.thlist.ServiceProvider> serviceprovider;

	public Exception() {
	}

	public java.util.List<com.th.thlist.ServiceProvider> getServiceprovider() {
		return this.serviceprovider;
	}

	public void setServiceprovider(
			java.util.List<com.th.thlist.ServiceProvider> serviceprovider) {
		this.serviceprovider = serviceprovider;
	}

	public Exception(
			java.util.List<com.th.thlist.ServiceProvider> serviceprovider) {
		this.serviceprovider = serviceprovider;
	}

}