package com.th.thlist;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Location implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String role;

	private java.lang.String service;

	public Location() {
	}

	public java.lang.String getRole() {
		return this.role;
	}

	public void setRole(java.lang.String role) {
		this.role = role;
	}

	public java.lang.String getService() {
		return this.service;
	}

	public void setService(java.lang.String service) {
		this.service = service;
	}

	public Location(java.lang.String role, java.lang.String service) {
		this.role = role;
		this.service = service;
	}

}