package com.th.thlist;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceProvider implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.th.thlist.Location> location;

	public ServiceProvider() {
	}

	public java.util.List<com.th.thlist.Location> getLocation() {
		return this.location;
	}

	public void setLocation(java.util.List<com.th.thlist.Location> location) {
		this.location = location;
	}

	public ServiceProvider(java.util.List<com.th.thlist.Location> location) {
		this.location = location;
	}

}